name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        
    - name: Display Go version
      run: go version

    - name: Change to backend directory
      run: cd backend

    - name: Install dependencies
      working-directory: ./backend
      run: go mod tidy

    - name: Change to app directory
      run: cd backend/cmd/app
      
    - name: Run local server
      run: |
        CGO_ENABLED=1 GOOS=linux go run main.go &
        sleep 10
        go test -count=1 -run ^TestApp$ ./tests
        
        
